### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Lisa999** [pfalcon/micropython-btreedb#5] opened 2017-09-25 23:04 UTC
From an ex-Oracle girl:
- Two additonal functions: Delete and Select
- Example ('example use' and 'example use: easydb', save the latter as db.py)
It's almost Oracle now... ;-)

**Comment by pfalcon** [comment] 2019-07-21 06:27
Apparent duplicate of https://github.com/pfalcon/pycopy-btreedb/issues/3.

**Closed as completed by pfalcon** 2019-07-21 06:27 UTC
