### ISSUE TITLE
Example use: EasyDB

### ISSUE THREAD

**Issue by Lisa999** [pfalcon/micropython-btreedb#4] opened 2017-09-25 23:01 UTC
from ucollections import OrderedDict
import ujson
import utime

import btreedb as uorm
import btree

db = uorm.DB("test.db")

class EasyDB(uorm.Model):

    # Create controller table
    __db__ = db
    __table__ = "testtable"
    __schema__ = OrderedDict([
        ("timestamp", ("TIMESTAMP", uorm.now)),
        ("test", ("INT", 0)),
    ])

**Comment by pfalcon** [comment] 2019-07-21 06:26
Apparent duplicate of https://github.com/pfalcon/pycopy-btreedb/issues/3.

**Closed as completed by pfalcon** 2019-07-21 06:26 UTC
